---
title: "R Notebook"
output: html_notebook
---

packages
```{r setup}
library(readr)
library(ggplot2)
library(dplyr)
library(NHSRdatasets)
library(plotly)

```

data pull
```{r}


phil_ae_attendances <- ae_attendances

phil_LOS_model <- LOS_model

write_csv(phil_ae_attendances, "phil_ae_attendances.csv")

phil_ae_attendances <- read_csv("phil_ae_attendances.csv")

phil_ae_attendances

```
Data Wrang

```{r}
wran_ae <- phil_ae_attendances %>%
 filter(period >= "2016-12-31" & period <= "2019-03-01") %>%
 filter(!(type %in% 
 "other"))

wran_ae

```


data viz 1
```{r}
dv1 <- ggplot(wran_ae) +
  aes(x = breaches) +
  geom_histogram(bins = 30L, fill = "#112446") +
  theme_minimal()

ggplotly(dv1)
```

data viz 2
```{r}
dv2 <- ggplot(wran_ae) +
  aes(x = breaches, y = attendances) +
  geom_point(shape = "circle", size = 1.5, colour = "#112446") +
  theme_minimal()

ggplotly(dv2)
```

```{r}


dv3 <- ggplot(wran_ae) +
 aes(x = breaches, y = attendances, colour = type) +
 geom_point(shape = "circle", size = 1.5) +
 scale_color_hue(direction = 1) +
 theme_minimal()

ggplotly(dv3)


```

